# Generated by Django 5.2.4 on 2025-08-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0003_alter_register_master_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminprofile_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Image')),
                ('Document', models.FileField(upload_to='Doc')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
