# Generated by Django 5.2.4 on 2025-09-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory_test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=30)),
                ('test_Price', models.IntegerField(default=10)),
            ],
        ),
    ]
