# Generated by Django 5.2.4 on 2025-08-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Master',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=12)),
                ('Feedback', models.CharField(max_length=1000)),
            ],
        ),
    ]
