# Generated by Django 5.2.4 on 2025-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Master',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=12)),
                ('Password', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('Role_Name', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
    ]
