# Generated by Django 5.2.4 on 2025-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_master',
            name='Email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
