# Generated by Django 5.2.4 on 2025-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_register_master_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_master',
            name='Status',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
