# Generated by Django 5.2.4 on 2025-09-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0003_alter_register_master_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientprofile_master',
            fields=[
                ('Patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Diesease', models.CharField(max_length=40)),
                ('Image', models.ImageField(upload_to='Image')),
                ('Document', models.FileField(upload_to='Doc')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
            ],
        ),
    ]
