# Generated by Django 5.2.4 on 2025-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile_master',
            name='Diesease',
        ),
        migrations.AddField(
            model_name='patientprofile_master',
            name='Diseases',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientprofile_master',
            name='Document',
            field=models.FileField(upload_to='Doc/'),
        ),
        migrations.AlterField(
            model_name='patientprofile_master',
            name='Image',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
