# Generated by Django 5.2.4 on 2025-09-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_doctor_appointment'),
        ('Register', '0003_alter_register_master_status'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTestReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register.register_master')),
                ('tests', models.ManyToManyField(to='Staff.laboratory_test')),
            ],
        ),
    ]
