# Generated by Django 5.2.4 on 2025-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_patienttestreport_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttestreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
