# Generated by Django 5.2.4 on 2025-09-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0004_patienttestreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.doctor_appointment')),
            ],
        ),
    ]
